### ISSUE TITLE
Molecule build issue

### ISSUE THREAD

**Issue by buluma** [buluma/ansible-role-logrotate#1]
## Describe the bug

Molecule build issue

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    tags_ignore:
      - '*'
  pull_request:
  schedule:
    - cron: '23 12 12 * *'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: molecule
        uses: buluma/molecule-action@v4.0.5
        with:
          command: lint
```

## Output

No config file found; using defaults[0m

## Environment

- Control node OS: [e.g. Debian 9] (`cat /etc/os-release`)
- Control node Ansible version: [e.g. 2.9.1] (`ansible --version`)
- Managed node OS: [e.g. CentOS 7] (`cat /etc/os-release`)
